### ISSUE TITLE
LRU sequence is incorrect

### ISSUE THREAD

**Issue by derek-groupmail** [Brokerloop/ttlcache#1]
I've noticed some issues where this library unexpectedly removes the wrong item from the cache because it's tracking of the least recently used gets messed up after a while.

This appears to happen whenever you set an item back into the cache which has the same key as an item present in the cache. When that happens, it appears that perhaps either the expiration time is incorrectly set or perhaps the prev/next linked list isn't correctly updated?

To try to narrow the issue down, I created a quick mocha test to set in the cache via various sequences and test the expected results. (I'm sure I could create a shorter sequence which illustrates the issue but this longer sequence below will do it.)

I'm inserting various items ('a' to 'q') in a sequence, **but the key point is that every now and then I'm setting the item 'a' (which already exists) back into the cache.** It's that particular operation I think that is messing up the cache and the tracking of the LRU item correctly.

The test starts to go wrong during Seq#7 below when the cache fills up (10 items max) and so has to start removing the LRU items to make room.
e.g.
`
  describe.only('LRU Insertions and Removals', () => {
    before(() => {
      // runs before all tests in this block
      ttlCache.clear();
      ttlCache.resize(10);
    });
    after(() => {
      // runs after all tests in this block
      ttlCache.clear();
    });

    describe('Multiple #set op sequences', () => {
      before(() => {
        // Seq 1 - Expected -> {abcd}
        ttlCache.set('a', 1);
        ttlCache.set('b', 2);
        ttlCache.set('c', 3);
        ttlCache.set('d', 4);

        // Seq 2 - Expected -> {bcda}
        ttlCache.set('a', 1);

        // Seq 3 - Expected -> {bcdaefgh}
        ttlCache.set('e', 5);
        ttlCache.set('f', 6);
        ttlCache.set('g', 7);
        ttlCache.set('h', 8);

        // Seq 4 - Expected -> {bcdefgha}
        ttlCache.set('a', 1);

        // Seq 5 - Expected -> {cdefghaijk}
        ttlCache.set('i', 9);
        ttlCache.set('j', 10);
        ttlCache.set('k', 11);

        // Seq 6 - Expected -> {cdefghijka}
        ttlCache.set('a', 1);

        // Seq 7 - Expected -> {ijkalmnopq}
        ttlCache.set('l', 12); // Expected -> {defghijkal}
        ttlCache.set('m', 13); // Expected -> {efghijkalm}
        ttlCache.set('n', 14); // Expected -> {fghijkalmn}, Actual -> {efghijklmn} and 'a' is evicted instead of 'e'!!!

        // LRU sequence is screwed after this, 
        // e.g. in the next stage, 'l' is evicted instead of 'e' which 
        // is really weird because 'l' was only just recently added!!!
        ttlCache.set('o', 15);
        ttlCache.set('p', 16);
        ttlCache.set('q', 17);
      });

      it('Set seq01 maintains LRU', () => expect([...ttlCache.keys()]).to.be.deep.equal(['i', 'j', 'k', 'a', 'l', 'm', 'n', 'o', 'p', 'q']));
      it('Set seq01 maintains newest', () => expect(ttlCache.newest.key).to.be.equal('q'));
      it('Set seq01 maintains oldest', () => expect(ttlCache.oldest.key).to.be.equal('i'));
    });
  });
`

I've ran the same test script through other alternative cache libraries and they produce the expected result, so there is something obviously wrong with this one. I see there are some basic unit tests in this library, but they could probably be extended with some more complex sequences.

It's a pity because this looks otherwise like a nice library, in particular I need a cache library which provides expire events such as this one, but I'm no longer confident it's been tested thoroughly enough. 

I've found that I can work around the issue if I issue a  .delete(key) before each and every set(key, value) which then seems to be handled correctly, but that's going to add some additional unnecessary overhead.

Thanks!

**Comment by soncodi** [comment]
Thanks for the thorough report. The eviction/iteration now handle your example, which I've added to the tests.

The iteration order (entries/keys/values) was backwards and has been reversed and clarified in the `README`. Additionally, `delete` behavior changed: it does not fire an `evict` signal anymore. These two changes were a major version bump.

Cheers!

**Comment by derek-groupmail** [comment]
This new version is all working perfectly for me now!
Thank you!
